import image from "@/public/images/doctor.png";

export const listingsData = [
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    id: "fefefeft4t4tg4t4t4tg",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    id: "fefefeft4t4tg4t4t4tg",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    id: "fefefeft4t4tg4t4t4tg",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    id: "fefefeft4t4tg4t4t4tg",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    id: "fefefeft4t4tg4t4t4tg",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    id: "fefefeft4t4tg4t4t4tg",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    id: "fefefeft4t4tg4t4t4tg",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    id: "fefefeft4t4tg4t4t4tg",
  },
];
