import image from "@/public/images/doctor.png";
import { ServicesProps } from "@/types";

export const servicesData: ServicesProps[] = [
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    url: "#",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    url: "#",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    url: "#",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    url: "#",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    url: "#",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    url: "#",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    url: "#",
  },
  {
    name: "Osmolality Measurement",
    equipment: "Membrane Osmometers",
    address: "2 Iyalla street Alausa Ikeja Lagos",
    count: 300,
    images: [image, image, image, image, image],
    ratings: 3,
    url: "#",
  },
];
