import type { Metadata } from "next";
import "@/src/styles/globals.scss";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import PrelineScript from "@/components/PrelineScript";
import ReactQueryProvider from "./providers/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { AppProviders } from "@/context";
import { Suspense } from "react";
import { LoadingState } from "@/components/common";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Suspense fallback={<LoadingState />}>
          <SessionProvider>
            <ReactQueryProvider>
              <AppProviders>
                <ToastContainer />
                {children}
              </AppProviders>
              <PrelineScript />
              <ReactQueryDevtools initialIsOpen={false} />
            </ReactQueryProvider>
          </SessionProvider>
        </Suspense>
      </body>
    </html>
  );
}
