import type { Metadata } from "next";
import "@/src/styles/globals.scss";
import NavBar from "@/components/navigation/web/NavBar";
import PrelineScript from "@/components/PrelineScript";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <NavBar />
        {children}
        <PrelineScript />
      </body>
    </html>
  );
}
