import type { Metadata } from "next";
import "@/src/styles/globals.scss";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import PrelineScript from "@/components/PrelineScript";
import ReactQueryProvider from "./providers/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { AuthProvider } from "@/context";
import { Suspense } from "react";
import { LoadingState } from "@/components/common";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Suspense fallback={<LoadingState />}>
          <ReactQueryProvider>
            <AuthProvider>
              <ToastContainer />
              {children}
            </AuthProvider>
            <PrelineScript />
            <ReactQueryDevtools initialIsOpen={false} />
          </ReactQueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
